#!/bin/bash

# librato-gauge metric value timestamp

curl  \
    -u $LIBRATO_USER:$LIBRATO_API_KEY \
    -d "gauges[0][name]=$1" \
    -d "gauges[0][value]=$2" \
    -d "gauges[0][timestamp]=$3" \
    -d "gauges[0][source]=`hostname`" \
    -X POST \
    https://metrics-api.librato.com/v1/metrics
